import BrandList from '@/components/brands/BrandList';
import BrandsHeader from '@/components/brands/BrandsHeader';
import Footer from '@/components/global/Footer';
import Meet from '@/components/home/Meet';
import Head from 'next/head';

const Brands = () => {
    return (
        <>
            <Head>
                <title>Brands - Motto Studio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <BrandsHeader />
            <BrandList />
            <Meet />
            <Footer />
        </>
    );
};

export default Brands;
