import Form from '@/components/contact/Form';
import styles from '../styles/contact/contact.module.css';
import { Fragment } from 'react';
import ContactHeader from '@/components/contact/ContactHeader';
import Info from '@/components/contact/Info';
import Footer from '@/components/global/Footer';
import Head from 'next/head';

const Contact = () => {
    return (
        <Fragment>
            <Head>
                <title>Contact - Motto Studio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ContactHeader />

            <div className={styles.container}>
                <Form />
                <Info />
            </div>

            <Footer />
        </Fragment>
    );
};

export default Contact;
