import Footer from '@/components/global/Footer';
import Clients from '@/components/home/Clients';
import Frame from '@/components/home/Frame';
import Header from '@/components/home/Header';
import LastCases from '@/components/home/LastCases';
import Meet from '@/components/home/Meet';
import Services from '@/components/home/Services';
import Button from '@/components/ui/Button';
import Head from 'next/head';

export default function Home() {
    return (
        <>
            <Head>
                <title>Motto Studio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />
            <Services />
            <Frame />
            {/* <Clients /> */}
            <LastCases />
            <Meet />
            <Footer />
        </>
    );
}
