import Footer from '@/components/global/Footer';
import Meet from '@/components/home/Meet';
import AIStudio from '@/components/services/AIStudio';
import Commitment from '@/components/services/Commitment';
import Frame from '@/components/services/Frame';
import ServiceList from '@/components/services/ServiceList';
import ServicesHeader from '@/components/services/ServicesHeader';
import TechStack from '@/components/services/TechStack';
import Head from 'next/head';

const Services = () => {
    return (
        <>
            <Head>
                <title>Services - Motto Studio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ServicesHeader />
            <Frame />
            <Commitment />
            <ServiceList />
            <AIStudio />
            <TechStack />
            <Meet />
            <Footer />
        </>
    );
};

export default Services;
