import Footer from '@/components/global/Footer';
import Frame from '@/components/studio/Frame';
import Meet from '@/components/home/Meet';
import StudioHeader from '@/components/studio/StudioHeader';
import Commitment from '@/components/studio/Commitment';
import Industries from '@/components/studio/Industries';
import AboutMotto from '@/components/studio/AboutMotto';
import Head from 'next/head';

const Studio = () => {
    return (
        <>
            <Head>
                <title>Studio - Motto Studio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <StudioHeader />
            <AboutMotto />
            <Frame />
            <Commitment />
            <Industries />
            <Meet />
            <Footer />
        </>
    );
};

export default Studio;
