import CaseHeader from '@/components/cases/CaseHeader';
import CaseList from '@/components/cases/CaseList';
import Footer from '@/components/global/Footer';
import Head from 'next/head';

const Cases = () => {
    return (
        <>
            <Head>
                <title>Case Studies - Motto Studio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <CaseHeader />
            <CaseList />
            <Footer />
        </>
    );
};

export default Cases;
